import { defineMermaidSetup } from '@slidev/types'

export default defineMermaidSetup(() => ({
  theme: 'base',
  themeVariables: {
    background: '#071426',
    primaryColor: '#0c2b4f',
    primaryTextColor: '#e8f7ff',
    primaryBorderColor: '#22d3ee',
    secondaryColor: '#102f50',
    secondaryTextColor: '#e8f7ff',
    secondaryBorderColor: '#38bdf8',
    tertiaryColor: '#13233d',
    tertiaryTextColor: '#cceeff',
    tertiaryBorderColor: '#3b82f6',
    lineColor: '#67e8f9',
    textColor: '#e8f7ff',
    mainBkg: '#0c2b4f',
    nodeBorder: '#22d3ee',
    clusterBkg: '#0a1f38',
    clusterBorder: '#256b8a',
    edgeLabelBackground: '#071426',
    actorBkg: '#0c2b4f',
    actorBorder: '#22d3ee',
    actorTextColor: '#e8f7ff',
    actorLineColor: '#4f8caf',
    signalColor: '#67e8f9',
    signalTextColor: '#dff8ff',
    noteBkgColor: '#12365d',
    noteBorderColor: '#38bdf8',
    noteTextColor: '#e8f7ff',
    labelBoxBkgColor: '#0c2b4f',
    labelBoxBorderColor: '#22d3ee',
    labelTextColor: '#e8f7ff',
  },
}))
